#https://github.com/gcovr/gcovr
#https://github.com/danielpalme/ReportGenerator
#https://github.com/atlaste/CPPCoverage

stages:
  - buildlib
  - buildtest
  - test

build-lib:
  stage: buildlib
  tags:
    - linux
  artifacts:
    paths:
      - "bin/"
  script:
    - make build

build-test:
  stage: buildtest
  tags:
    - linux
  artifacts:
    paths:
      - "bin/"
  script:
    - make build-test

run-tests:
  stage: test
  tags:
    - linux
  needs: ["build-test"]
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: bin/test-coverage.xml
  script:
    - make test
