#https://github.com/gcovr/gcovr
#https://github.com/danielpalme/ReportGenerator
#https://github.com/atlaste/CPPCoverage

stages:
  - build
  - run

# build-tests:
# run-tests:
    
build-coverage:
  stage: build
  tags:
    - linux
  artifacts:
    paths:
      - "bin/"
  script:
    - make build-coverage    

run-coverage:
  stage: run
  tags:
    - linux
  needs: ["build-coverage"]
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: bin/test-coverage.xml
  script:
    - make run-coverage

build-release:
  stage: build
  tags:
    - linux
  artifacts:
    paths:
      - "bin/"
  script:
    - make build-release